version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: smrtmart_postgres
    environment:
      POSTGRES_DB: smrtmart_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - smrtmart_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    container_name: smrtmart_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - smrtmart_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # SmartMart API
  api:
    build: .
    container_name: smrtmart_api
    ports:
      - "8080:8080"
    environment:
      # Database
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: ${POSTGRES_PASSWORD:-}
      DB_NAME: smrtmart_db
      DB_SSLMODE: disable
      
      # Server
      PORT: 8080
      GIN_MODE: release
      CORS_ORIGINS: https://smrtmart.com,https://www.smrtmart.com,http://localhost:3000
      
      # JWT
      JWT_SECRET: ${JWT_SECRET:-}
      
      # Stripe (replace with your actual keys)
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY:-}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET:-}
      
      # Upload
      UPLOAD_PATH: ./uploads
      MAX_UPLOAD_SIZE: 10485760
      
      # Redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
    volumes:
      - ./uploads:/root/uploads
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - smrtmart_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  redis_data:

networks:
  smrtmart_network:
    driver: bridge